#!/usr/bin/perl
#
# simple perl script to execute Jixee webhook on self hosted git
# 
# tabstop=8
#

use strict;

##########
## vars ##
##########

my $in=<STDIN>;
my @args=split(/\s/,$in);

my $old=$args[0];
my $new=$args[1];
my $ref=$args[2];

## these vars we'll use to build our json post ##
my $branch;
my @commits;
my $commitid;
my $commitmsg;
my $committer;
my $id;
my $json;
my $timestamp;


my $DEBUG=0;
my $LOG="/tmp/hooktest.log";

## debug
if ($DEBUG) {
    open(WRITE,">>$LOG") || die "Can't open $LOG: $!\n";
}


## EDIT THESE VARIABLES AND ENTER YOUR JIXEE API/WEBHOOK URL, as well as your repo name
##
## Examples: 
## my $webhook='https://jixee.me/main/webhooks?token=ff7133a6e7c129fd9bb63695015553e047c9d366';
## my $repo='jixee-api';
my $webhook='';
my $repo='';

## let's check to see if this is a tag, and if so, just exit
if ($in =~ /.*refs\/tags.*/ ) {
    exit;
}

## let's get the commit message so we can parse it
my $rip=`git rev-list --reverse --date=iso --pretty --stdin $old..$new`;

## first parse the commits
@commits = split(/commit/,$rip);
my $i=0;
foreach my $c (@commits) {
    $i++;
    ## debug
    if ($DEBUG) {
        print WRITE  "$i: $c\n";
    }

    ## remove newlines to make regex easier to debug (could use s modifier too, but like this better)
    $c=~ s/\n//g;

    ## let's first see if the commit message contains a Jixee Task ID and if not, do nothing
    if ($c =~ /.*\[id:([\w\d-]+)\].*\[?.*/ || $c =~ /.*?([a-zA-z]{1,3}\-\d+):.*?/) {
    #if ($c =~ /.*?([a-zA-z]{1,3}\-\d+:.*).*?/) {
            $id=$1;
            ## Task ID found, let's pull the info we need
            if ($c =~ /\s+([\w\d]+).*Author:(.*)\<.*Date:\s*(\d{4}-\d{2}-\d{2}\s\d{2}:\d{2}:\d{2}\s\W{1}\d{4})\s*(.*)/s) {
                $commitid=$1;
                $committer=$2;
                $timestamp=$3;
                $commitmsg=$4;
		$timestamp=~ s|^(\d{4}-\d{2}-\d{2})\s(\d{2}:\d{2}:\d{2})\s(\W{1})(\d{2})(\d{2})$|$1T$2$3$4:$5|;
                $commitmsg=~ s/\'//g;
                $commitmsg=~ s/\"//g;
		## let's grab the branch this commit is from
		$branch=`git branch --contains=$commitid`;
		$branch=~ s/\*\s//g;
		$branch=~ s/\n//g;
                $json='{"action":"version","task_id":"'.$id.'", "commit_id":"'.$commitid.'","committer":{"name":"'.$committer.'"},"timestamp":"'.$timestamp.'", "message":"'.$commitmsg.'", "repository":"'.$repo.'","branch":"'.$branch.'"}';
                ## debug
                if ($DEBUG) {
                    print WRITE "curl -H \"Content-Type: application/json\" -s -X POST -d \'$json\' $webhook > /dev/null\n";
                }
                system("curl -H \"Content-Type: application/json\" -s -X POST -d \'$json\' $webhook >> /tmp/post-receive-output");
            }
    }
}

## debug
if ($DEBUG) {
    close(WRITE);
}
